# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88226e690fe1de777f4ad13fc5818f8ac697e33cfa8a526224720bc90111b050dab36037f0bcdaafe450bd3640c08767323aa638f4a62e8c26bee86cdc9b894f

test:
  secret_key_base: ee67fcb4ea12191b5615b3d0c6a5e4aaa4b2661a12be0262790f2220d0e448cfa005123392a095cef99c9770bcb144626ed6ef2a1e0c98f93a4f5682642ec7a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
